ACLOCAL_AMFLAGS = -I m4

SUBDIRS = src 

pkgdataimgdir = $(pkgdatadir)/imgs
pkgdataimg_DATA = imgs/disgrace.png

EXTRA_DIST = \
    $(pkgdataimg_DATA) \
    README.md \
    AUTHORS \
    LICENSE \
    NEWS \
    dist/freebsd/Makefile \
    dist/freebsd/distinfo \
    dist/freebsd/pkg-descr \
    dist/freebsd/README \
    dist/debian/control \
    dist/debian/rules \
    dist/debian/changelog \
    dist/debian/copyright \
    dist/debian/source/format \
    dist/debian/disgrace.1 \
    dist/debian/README \
    dist/gentoo/metadata/layout.conf \
    dist/gentoo/media-sound/disgrace/disgrace-0.1.1.ebuild \
    dist/gentoo/media-sound/disgrace/metadata.xml \
    dist/gentoo/README
