/*
 * Disgrace - Digital Audio Workstation
 * Copyright (C) 2025  Miroslav Shaltev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "lilypond_exporter.h"
#include "../core/engine.h"
#include "../sequencer/pattern.h"
#include "../mixer/track.h"
#include "../instrument/instrument.h"
#include <fstream>
#include <sstream>
#include <map>

namespace disgrace_ns {

// Maps a MIDI note number to LilyPond's absolute pitch notation.
std::string LilyPondExporter::midi_to_lily(uint8_t note) {
    if (note >= 128) return "r"; // Return a rest for invalid notes
    
    static const char* names[] = {"c", "cis", "d", "dis", "e", "f", "fis", "g", "gis", "a", "ais", "b"};
    int pitch = note % 12;
    int octave = note / 12;
    
    // LilyPond absolute pitch: 
    // c' is Middle C (C4, MIDI 60)
    // c is C3 (MIDI 48)
    // c, is C2 (MIDI 36)
    // disgrace uses octave 5 for 60-71
    std::string s = names[pitch];
    int lily_octave = octave - 5; 

    if (lily_octave > 0) {
        for (int i = 0; i < lily_octave; ++i) s += "'";
    } else if (lily_octave < 0) {
        for (int i = 0; i < -lily_octave; ++i) s += ",";
    }
    
    return s;
}

// Maps a MIDI note to LilyPond drum names for \drummode.
std::string midi_to_drum(uint8_t note) {
    // Basic GM Drum Map to LilyPond percussion names
    switch (note) {
        case 35: case 36: return "bd";   // Bass Drum
        case 37:          return "ss";   // Side Stick
        case 38: case 40: return "sn";   // Snare
        case 39:          return "hc";   // Hand Clap
        case 41: case 43: return "toml"; // Low Tom
        case 42:          return "hhc";  // Closed Hi-hat
        case 44:          return "hhp";  // Pedal Hi-hat
        case 45: case 47: return "tomm"; // Mid Tom
        case 46:          return "hho";  // Open Hi-hat
        case 48: case 50: return "tomh"; // High Tom
        case 49:          return "cymc"; // Crash Cymbal
        case 51:          return "cymr"; // Ride Cymbal
        case 52:          return "cymc"; // Chinese Cymbal
        case 53:          return "rb";   // Ride Bell
        case 54:          return "tamb"; // Tambourine
        case 55:          return "cyms"; // Splash Cymbal
        case 56:          return "cb";   // Cowbell
        case 57:          return "cymc"; // Crash 2
        case 59:          return "cymr"; // Ride 2
        default:          return "bd";   // Fallback to bass drum
    }
}

// Returns the clef string based on the track's notation type.
std::string LilyPondExporter::get_clef_string(int notation_type) {
    switch (static_cast<NotationType>(notation_type)) {
        case NotationType::Violin: return "treble";
        case NotationType::Bass: return "bass";
        case NotationType::ViolinBass: return "treble"; 
        case NotationType::Drums: return "percussion";
        default: return "treble";
    }
}

// Generates the .ly source code for the entire project or a single track.
std::string LilyPondExporter::generate_ly_source(const Engine& engine, int track_index) {
    auto get_track_id = [](int t) {
        std::string id = "track";
        int n = t;
        std::string suffix = "";
        do {
            suffix = (char)('a' + (n % 26)) + suffix;
            n = (n / 26) - 1;
        } while (n >= 0);
        id += suffix;
        return id;
    };

    std::stringstream ss;
    ss << R"(\version "2.24.0")" << "\n\n";
    ss << R"(\header {)" << "\n";
    ss << "  title = \"" << engine.project_title() << "\"\n";
    ss << "  composer = \"" << engine.project_artist() << "\"\n";
    if (!engine.project_album().empty()) {
        ss << "  meter = \"" << engine.project_album() << "\"\n";
    }
    if (!engine.project_year().empty()) {
        ss << "  copyright = \"" << engine.project_year() << "\"\n";
    }
    ss << R"(  tagline = "Generated by Disgrace Tracker DAW")" << "\n";
    ss << R"(})" << "\n\n";

    auto order = engine.order_list();
    size_t num_tracks = engine.track_count();

    // Lambda to process a single track's data into LilyPond format.
    auto process_track = [&](size_t t) {
        const auto& track_obj = engine.track(t);
        NotationType ntype = track_obj.notation();
        
        ss << get_track_id((int)t) << " = ";
        if (ntype == NotationType::Drums) ss << "\\drummode ";
        
        ss << "{\n";
        
        // We use absolute pitches now, so no \relative
        for (auto pat_idx : order) {
            const auto& pat = engine.pattern(pat_idx);
            int pat_rows = (int)pat.row_count();
            
            for (int r = 0; r < pat_rows; ++r) {
                // Use the first note found in any column of the row
                bool note_found = false;
                for (size_t c = 0; c < pat.column_count(t); ++c) {
                    const auto& ev = pat.event(t, r, c);
                    if (ev.note < 128) {
                        if (ntype == NotationType::Drums) {
                            ss << midi_to_drum(ev.note) << "16 ";
                        } else {
                            ss << midi_to_lily(ev.note) << "16 ";
                        }
                        note_found = true;
                        break; 
                    }
                }
                if (!note_found) {
                    ss << "r16 "; // Rest if no note is found in the row
                }
                if ((r + 1) % 16 == 0) ss << "| % row " << r << "\n  ";
            }
        }
        ss << "\n}\n\n";
    };

    if (track_index == -1) { // Exporting the whole project
        for (size_t t = 0; t < num_tracks; ++t) {
            const auto& track_obj = engine.track(t);
            if (track_obj.instrument() && (track_obj.instrument()->type() == InstrumentType::SoundFont || track_obj.instrument()->type() == InstrumentType::Plugin || track_obj.instrument()->type() == InstrumentType::Midi)) {
                 process_track(t);
            }
        }

        ss << "\\score {\n  <<\n";
        for (size_t t = 0; t < num_tracks; ++t) {
            const auto& track_obj = engine.track(t);
             if (track_obj.instrument() && (track_obj.instrument()->type() == InstrumentType::SoundFont || track_obj.instrument()->type() == InstrumentType::Plugin || track_obj.instrument()->type() == InstrumentType::Midi)) {
                NotationType ntype = track_obj.notation();
                std::string tid = "\\" + get_track_id((int)t);
                
                if (ntype == NotationType::ViolinBass) {
                    ss << "    \\new PianoStaff \\with { instrumentName = #\"" << track_obj.name() << "\" } <<\n";
                    ss << "      \\new Staff { \\clef treble \\time 4/4 " << tid << " }\n";
                    ss << "      \\new Staff { \\clef bass \\time 4/4 " << tid << " }\n";
                    ss << "    >>\n";
                } else if (ntype == NotationType::Drums) {
                    ss << "    \\new DrumStaff \\with { instrumentName = #\"" << track_obj.name() << "\" } << \\time 4/4 " << tid << " >>\n";
                } else {
                    ss << "    \\new Staff \\with { instrumentName = #\"" << track_obj.name() << "\" } << \\clef " << get_clef_string((int)ntype) << " \\time 4/4 " << tid << " >>\n";
                }
            }
        }
        ss << "  >>\n  \\layout { }\n  \\midi { }\n}\n";
    } else { // Exporting a single track
        process_track(track_index);
        const auto& track_obj = engine.track(track_index);
        NotationType ntype = track_obj.notation();
        std::string tid = "\\" + get_track_id(track_index);

        ss << "\\score {\n";
        if (ntype == NotationType::ViolinBass) {
            ss << "  \\new PianoStaff <<\n";
            ss << "    \\new Staff { \\clef treble \\time 4/4 " << tid << " }\n";
            ss << "    \\new Staff { \\clef bass \\time 4/4 " << tid << " }\n";
            ss << "  >>\n";
        } else if (ntype == NotationType::Drums) {
            ss << "  \\new DrumStaff << \\time 4/4 " << tid << " >>\n";
        } else {
            ss << "  \\new Staff << \\clef " << get_clef_string((int)ntype) << " \\time 4/4 " << tid << " >>\n";
        }
        ss << "  \\layout { }\n}\n";
    }

    return ss.str();
}

// Writes the generated .ly source to a file.
bool LilyPondExporter::export_project(const Engine& engine, const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return false;
    f << generate_ly_source(engine);
    return f.good();
}

} // namespace disgrace_ns
