bin_PROGRAMS = disgrace dssi_sandbox

disgrace_SOURCES = \
    main.cpp \
    core/engine.cpp \
    core/engine_save.cpp \
    core/config_manager.cpp \
    core/key_bindings.cpp \
    core/masterbus.cpp \
    core/metronome.cpp \
    core/transport.cpp \
    core/undo_stack.cpp \
    audio/jack_backend.cpp \
    audio/oss_backend.cpp \
    audio/resampler.cpp \
    audio/sample_buffer.cpp \
    audio/sample_voice.cpp \
    audio/timestretch.cpp \
    dsp/dsp_chain.cpp \
    dsp/reference_analyzer.cpp \
    dsp/reference_matcher.cpp \
    edit/cmd_track_cut.cpp \
    edit/cmd_track_copy.cpp \
    edit/cmd_track_paste.cpp \
    edit/cmd_track_silence.cpp \
    edit/cmd_track_insert_silence.cpp \
    gui/wx_main_window.cpp \
    gui/wx_project_panel.cpp \
    gui/wx_detached_frame.cpp \
    gui/wx_tracker_panel.cpp \
    gui/wx_tracker_view.cpp \
    gui/wx_tracks_panel.cpp \
    gui/wx_notation_panel.cpp \
    gui/wx_instrument_panel.cpp \
    gui/wx_mixer_panel.cpp \
    gui/wx_settings_panel.cpp \
    gui/wx_help_panel.cpp \
    gui/wx_startup_dialog.cpp \
    gui/wx_vu_meter.cpp \
    gui/wx_analog_vu_meter.cpp \
    gui/wx_waveform_view.cpp \
    gui/wx_spectral_view.cpp \
    gui/wx_transportbar.cpp \
    gui/model/mixer_model.cpp \
    gui/theme.cpp \
    instrument/instrument.cpp \
    instrument/instrument_rack.cpp \
    instrument/sample_instrument.cpp \
    instrument/soundfont_instrument.cpp \
    instrument/sfz_instrument.cpp \
    instrument/xrni_instrument.cpp \
    instrument/dssi_instrument.cpp \
    instrument/lv2_instrument.cpp \
    instrument/midi_instrument.cpp \
    instrument/voice_instrument.cpp \
    instrument/voice_synthesis_worker.cpp \
    io/audio_file.cpp \
    io/lilypond_exporter.cpp \
    io/project_archive.cpp \
    io/song_serializer.cpp \
    io/xrns_importer.cpp \
    io/midi_importer.cpp \
    midi/midi_input.cpp \
    mixer/track.cpp \
    mixer/track_clipboard.cpp \
    mixer/mixer_bus.cpp \
    sequencer/automation.cpp \
    sequencer/pattern.cpp \
    sequencer/sequencer.cpp \
    sequencer/timing.cpp \
    analysis/fft_analyzer.cpp \
    analysis/onset_detector.cpp \
    audio/beat_quantizer.cpp \
    gui/wx_beat_quantize_dialog.cpp

dssi_sandbox_SOURCES = instrument/dssi_sandbox_main.cpp
dssi_sandbox_CXXFLAGS = $(ALSA_CFLAGS)
dssi_sandbox_LDADD = $(ALSA_LIBS) -ldl -lrt

# Headers are not compiled directly but must ship in `make dist` tarballs.
noinst_HEADERS = \
    analysis/fft_analyzer.h \
    analysis/onset_detector.h \
    analysis/pitch_detector.h \
    audio/adsr.h \
    audio/audio_backend.h \
    audio/beat_quantizer.h \
    audio/jack_backend.h \
    audio/null_backend.h \
    audio/oss_backend.h \
    audio/resampler.h \
    audio/sample_buffer.h \
    audio/sample_data.h \
    audio/sample_voice.h \
    audio/timestretch.h \
    audio/voice.h \
    core/app_info.h \
    core/audio_thread_pool.h \
    core/command.h \
    core/config_manager.h \
    core/engine_command.h \
    core/engine.h \
    core/key_bindings.h \
    core/masterbus.h \
    core/metronome.h \
    core/theme_types.h \
    core/transport.h \
    core/undo_stack.h \
    dsp/cabinet.h \
    dsp/chorus.h \
    dsp/compressor.h \
    dsp/delay.h \
    dsp/distortion.h \
    dsp/dsp_chain.h \
    dsp/dsp.h \
    dsp/echo.h \
    dsp/exciter.h \
    dsp/flanger.h \
    dsp/gain.h \
    dsp/gate.h \
    dsp/graphical_eq.h \
    dsp/limiter.h \
    dsp/mastering_filter.h \
    dsp/mastering_styles.h \
    dsp/phaser.h \
    dsp/reference_analyzer.h \
    dsp/reference_matcher.h \
    dsp/reverb.h \
    dsp/ring_modulator.h \
    dsp/stereo_expander.h \
    dsp/vocoder.h \
    edit/cmd_clear_block.h \
    edit/cmd_edit_block.h \
    edit/cmd_paste_block.h \
    edit/cmd_set_note.h \
    edit/cmd_track_copy.h \
    edit/cmd_track_cut.h \
    edit/cmd_track_insert_silence.h \
    edit/cmd_track_paste.h \
    edit/cmd_track_silence.h \
    edit/edit_command.h \
    edit/undo_stack.h \
    gui/model/mixer_model.h \
    gui/theme.h \
    gui/tracker_widget.h \
    gui/wx_analog_vu_meter.h \
    gui/wx_beat_quantize_dialog.h \
    gui/wx_detached_frame.h \
    gui/wx_help_panel.h \
    gui/wx_instrument_panel.h \
    gui/wx_main_window.h \
    gui/wx_mixer_panel.h \
    gui/wx_notation_panel.h \
    gui/wx_project_panel.h \
    gui/wx_settings_panel.h \
    gui/wx_spectral_view.h \
    gui/wx_startup_dialog.h \
    gui/wx_tracker_panel.h \
    gui/wx_tracker_view.h \
    gui/wx_tracks_panel.h \
    gui/wx_transportbar.h \
    gui/wx_vu_meter.h \
    gui/wx_waveform_view.h \
    instrument/dssi_bridge_shm.h \
    instrument/dssi_instrument.h \
    instrument/instrument.h \
    instrument/instrument_rack.h \
    instrument/lv2_instrument.h \
    instrument/midi_instrument.h \
    instrument/sample_instrument.h \
    instrument/sfz_instrument.h \
    instrument/soundfont_instrument.h \
    instrument/voice_instrument.h \
    instrument/voice_synthesis_worker.h \
    instrument/xrni_instrument.h \
    io/audio_file.h \
    io/lilypond_exporter.h \
    io/midi_importer.h \
    io/project_archive.h \
    io/song_serializer.h \
    io/xrns_importer.h \
    midi/midi_input.h \
    midi/midi_queue.h \
    mixer/mixer_bus.h \
    mixer/track_clipboard.h \
    mixer/track.h \
    sequencer/automation.h \
    sequencer/note.h \
    sequencer/pattern.h \
    sequencer/sequencer.h \
    sequencer/timing.h \
    util/linear_smoother.h \
    util/ringbuffer.h

disgrace_CXXFLAGS = \
    $(JACK_CFLAGS) \
    $(WXWIDGETS_CFLAGS) \
    $(SNDFILE_CFLAGS) \
    $(SAMPLERATE_CFLAGS) \
    $(ESPEAK_CFLAGS) \
    $(FESTIVAL_CFLAGS) \
    $(PIPER_CFLAGS) \
    $(SNDTOUCH_CFLAGS) \
    $(NLOHMANN_JSON_CFLAGS) \
    $(FFTW3_CFLAGS) \
    $(LIBARCHIVE_CFLAGS) \
    $(FLUIDSYNTH_CFLAGS) \
    $(ALSA_CFLAGS) \
    $(LIBXML2_CFLAGS)

disgrace_LDADD = \
    $(JACK_LIBS) \
    $(WXWIDGETS_LIBS) \
    $(SNDFILE_LIBS) \
    $(SAMPLERATE_LIBS) \
    $(ESPEAK_LIBS) \
    $(FESTIVAL_LIBS) \
    $(PIPER_LIBS) \
    $(SNDTOUCH_LIBS) \
    $(FFTW3_LIBS) \
    $(LIBARCHIVE_LIBS) \
    $(FLUIDSYNTH_LIBS) \
    $(LIBXML2_LIBS) \
    -lrt
